ALTER TABLE contacts ADD COLUMN IF NOT EXISTS url TEXT;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS gender TEXT;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS list_type TEXT;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS status TEXT;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS prefecture TEXT;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS notes TEXT;
